### ISSUE TITLE
add TypeScript definitions

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/cypress-cdp#27]
to provide types for `cy.CDP` command

**Comment by froissant** [comment]
Hi @bahmutov !
I tried to add TypeScript definitions to your module, since I wanted to use it in a project.
Let me know if you have comments. Feel free to integrate the definitions in your module directly if they suit you!

**Comment by bahmutov** [comment]
This is a good idea, but let's not add it to definitelytype, you can add it directly to this package, if you open a PR
