### ISSUE TITLE
hasEventListeners doesn't support JQuery selectors

### ISSUE THREAD

**Issue by gofr** [bahmutov/cypress-cdp#3]
You do a sanity check with `cy.get()`, but if I use a selector like `button:contains('Submit')` this sanity check will pass, but the `'frames[0].document.querySelector("' + selector + '")'` expression fails because it doesn't support this fancy non-CSS selector.

Could this do `'Cypress.$("' + selector + '")[0]'` instead?

**Comment by bahmutov** [comment]
Do you want to open a pull request with a test plus a fix?

**Comment by gofr** [comment]
In theory yes, but in practice I'm not sure when I'll have the time.
